site_name: KimHao Nguyen (Nguyen Duong Kim Hao)
site_url: https://ndkimhao.github.io
site_description: KimHao Nguyen (Nguyen Duong Kim Hao). Computer Science and Engineering Department, University of Nebraska-Lincoln.
site_author: KimHao Nguyen
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: fontawesome/brands/neos
  favicon: images/favicon.png
  features:
    - navigation.tabs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
nav:
  - index.md
  - publications.md
  - awards.md
  - projects.md
  - contact.md
