site_name: KimHao Nguyen
site_url: http://ndkimhao.github.io
site_description: KimHao Nguyen's Personal Homepage
site_author: KimHao Nguyen
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: fontawesome/brands/neos
  favicon: images/favicon.png
  features:
    - navigation.tabs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
nav:
  - index.md
  - publications.md
  - awards.md
